development:
  adapter: mysql
  database: theplanforus_development
  username: root

test:
  adapter: mysql
  database: theplanforus_test
  username: root

production:
  adapter: mysql
  database: theplanforus_production
  username: root
